name: compile

on:
  push:
     branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build:

    runs-on: windows-latest

    steps:

      - uses: actions/checkout@v4

      - run: dotnet build -c Release

      - run: dotnet publish

      - uses: actions/upload-artifact@v4

        with:

          name: ultgt2downloader

          path: ./bin/Release/net8.0-windows10.0.17763.0

      
